### PR TITLE
Support react native 0.26+

### PR DESCRIPTION
**Pull request by cpunion**
Minimal changes to avoid native compatible problem.

### CODE REVIEW

**Comment by cpunion** [comment]
I'm trying upgrade to react native 0.35, because lower versions can't compile on macOS 10.12 and Xcode 8.

**Comment by cpunion** [comment]
And what's the license of this project?

**Comment by danscan** [comment]
@cpunion Just added the MIT license.  Looking at this PR now. :)

**Comment by danscan** [comment]
@cpunion I just added a couple more commits in addition to your work via PR #3.  Thanks for doing this!  Will squash and merge momentarily.

**Comment by cpunion** [comment]
Awesome!

**Pull request closed without merging**
